# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-22 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palev', '0002_auto_20191022_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
