# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-14 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palev', '0003_article_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_link', models.CharField(max_length=50)),
                ('page_title', models.CharField(max_length=100)),
                ('page_content', models.TextField()),
            ],
        ),
    ]
