# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-14 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palev', '0004_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_link',
            field=models.CharField(max_length=100),
        ),
    ]
