# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-14 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palev', '0005_auto_20191114_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_title',
            field=models.CharField(max_length=255),
        ),
    ]
